HPP = util.hpp vetorDes.hpp vetorOrd.hpp arvoreBin.hpp  treap.hpp arvore23.hpp tabeladesimbolos.hpp arvoreRN.hpp hashTable.hpp listaDes.hpp listaOrd.hpp 

unit_test: $(HPP)
  g++ unit_test.o -o unit_test -lm

unit_test.o: unit_test.cpp $(HPP)